#!/bin/bash
set -e
npm --prefix pSSIDGUI-root/main/main_spa install
npm --prefix pSSIDGUI-root/main/main_spa run build -- --mode staging 
export SECRET_KEY=fjbgskjdfhvg
python3 pSSIDGUI-root/manage.py collectstatic --no-input
python3 pSSIDGUI-root/manage.py migrate
python3 pSSIDGUI-root/manage.py runserver $1
