version: '2'

services:
  web:
    build: ./pSSIDGUI-root
    container_name: django
    command: gunicorn pSSIDGUI.wsgi:application --bind 0.0.0.0:8000
    ports:
      - ${PORT}:8000
    volumes:
      - ${INV_DIR}:/app/inventories:Z

