version: '3.8'

services:
  web:
    build: ./src
    container_name: pssid-gui
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - ${PORT}:8000
    volumes:
      - ${INV_DIR}:/app/inventories:Z
    dns:
      - 9.9.9.9
      - 8.8.8.8

