version: '2'

services:
  web:
    build: ./pSSIDGUI-root
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    expose: [ 8000 ]
    env_file:
      - ./.env
    volumes:
      - ./inventories:/app/inventories:Z
      # includes ansible inventory
  nginx:
    build: ./nginx
    volumes_from: 
      - web
    ports:
      - 8080:80
    depends_on:
      - web
