amqp_url: "amqp://{{ amqp_user }}:{{ amqp_passwd }}@pssid-elk.miserver.it.umich.edu"

archives:
  - name:  "rabbitmq_archive"
    archiver: "rabbitmq"
    data: {
      _url: "{{ amqp_url }}",
      routing-key: "pscheduler_raw"
    }

  - name:  "syslog_archive"
    archiver: "syslog"
    data: {
      ident: "pSSID test result",
      facility : "local3"
    }
