BSSID_channels:
  - name: "eduroam_channels"
    channels: [1, 6, 11, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165]
  - name: "MWireless_channels"
    channels: [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165]
  - name: "MSetup_channels"
    channels: [1, 6, 11, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165]

SSID_profiles:
  - name: "MWireless_profile"
    SSID: "MWireless"
    channels: "MWireless_channels"
    channel_mismatch_warning: "true"
    channel_mismatch_connect: "false"
    min_signal: -73
    min_qualifying: 2
    auth: "true"
    type: "user"
    identity: "{{ MWireless_identity }}"
    password: "{{ MWireless_wpa_passwd }}"
    paranoid: "false"
    pscheduler_restart: "false"
    apache_restart: "false"
    postgres_restart: "false"
    wait_time: 0
  - name: "eduroam_profile"
    SSID: "eduroam"
    channels: "eduroam_channels"
    channel_mismatch_warning: "true"
    channel_mismatch_connect: "false"
    min_signal: -65
    min_qualifying: 2
    auth: "true"
    type: "user"
    identity: "{{ eduroam_identity }}"
    password: "{{ eduroam_wpa_passwd }}"
    paranoid: "true"
    pscheduler_restart: "false"
    apache_restart: "false"
    postgres_restart: "false"
    wait_time: 0
  - name: "MSetup_profile"
    SSID: "MSetup"
    channels: "MSetup_channels"
    channel_mismatch_warning: "true"
    channel_mismatch_connect: "false"
    min_signal: -65
    min_qualifying: 2
    auth: "true"
    type: "macaddress"
    num_addresses: 3,
    macaddresses: [
      "{{macaddress1}}",
      "{{macaddress2}}",
      "{{macaddress3}}"
    ]
    identity: 'temp'
    password: 'temp'
    paranoid: "true"
    pscheduler_restart: "false"
    apache_restart: "false"
    postgres_restart: "false"
    wait_time: 0

SSID_groups:
  - name: "all_profiles"
    group: ["eduroam_profile", "MWireless_profile", "MSetup_profile"]
  - name: "WPA_encrypted_profiles"
    group: ["eduroam_profile", "MWireless_profile"]

BSSID_scans:
  - name: "primary_BSSIDs"
    interface: "primary_network_interface"
    profiles: "all_profiles"
    unknown_SSID_warning: "true"
    schedule: [ "schedule_every_5_min" ]
    priority: 1
    meta_information: "probe_stats"
