pssid_tasks: 
  - name: "throughput"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "throughput_perfsonar_seb" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule:  [ "schedule_every_1_hour", "schedule_at_minute_30" ]
    priority: 2
    ttl: 120
    meta_information: "probe_stats"
    throughput_threshold: 95000000
  - name: "latency"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "latency_perfsonar_seb" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_at_minute_10", "schedule_at_minute_40" ]
    priority: 3 
    ttl: 120
    meta_information: "probe_stats"
  - name: "http"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "http_mguest_portal" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_at_minute_20", "schedule_at_minute_50"]
    priority: 4
    ttl: 120
    meta_information: "probe_stats"