tests:
  - name: "test_rtt"
    type: "rtt"
    spec: {
      dest: "www.umich.edu"
    }
  - name: "latency_perfsonar_seb"
    type: "latency"
    spec: {
      dest: "perfsonar-bin-seb.umnet.umich.edu"
    }
  - name: "throughput_perfsonar_seb"
    type: "throughput"
    spec: {
      dest: "perfsonar-bin-seb.umnet.umich.edu"
    }
  - name: "http_mguest_portal"
    type: "http"
    spec: {
      url: "http://portal-mguest-lb.dsc.umich.edu"
    }
  - name: "test_latency"
    type: "latency"
    spec: {
      dest: "perfsonar-bin-arbl.umnet.umich.edu"
    }
  - name: "test_throughput_ul"
    type: "throughput"
    spec: {
      dest: "perfsonar-bin-arbl.umnet.umich.edu"
    }
  - name: "test_throughput_dl"
    type: "throughput"
    spec: {
      source: "perfsonar-bin-arbl.umnet.umich.edu"
    }
  - name: "test_http_umich"
    type: "http"
    spec: {
      url: "http://umich.edu"
    }
  - name: "test_http_google"
    type: "http"
    spec: {
      url: "http://google.com"
    }
  - name: "test_dns_a"
    type: "dns"
    spec: {
      query: "www.umich.edu",
      record: "a"
    }
  - name: "test_dns_aaaa"
    type: "dns"
    spec: {
      query: "www.umich.edu",
      record: "aaaa"
    }
