- name: Generate pSSID config file
  hosts: all

  tasks:

  # local machine (Ansible controller/web server),
  # essentially a log
  - name: make the local pSSID config dir if it doesn't exist
    file:
      path: /etc/pssid/configs
      state: directory
    delegate_to: localhost

  - name: generate pSSID config file locally
    template:
      src: ./pssid-conf.j2
      dest: /etc/pssid/configs/{{ ip }}.json
    delegate_to: localhost

  # remote machine
  - name: make the remote pSSID config dir if it doesn't exist
    file:
      path: /etc/pssid
      state: directory
  - name: generate pSSID config file on target
    template:
      src: ./pssid-conf.j2
      dest: /etc/pssid/config.json

  - name: create the pscheduler secrets folder on the remote machine
    file:
      path: /etc/pscheduler/tests/ssid
      state: directory
      owner: root
      group: root
      mode: 0400
      recurse: yes # also apply 0400 to subfolders/subfiles

  - name: generate the SSID passwords file on the remote machine
    template: 
      src: ./logins.json
      # dest will change once we decide on specifics
      dest: /etc/pscheduler/tests/ssid/creds.json

